"""
models/schemas.py
==============================================================================
Pydantic data models for structured content generated by the LLM
(interview Q&A, quiz questions, flashcards) and for internal app state.

Why Pydantic here specifically (vs. plain dataclasses used in config.py):
    LLM output is UNTRUSTED, semi-structured text coerced from JSON. We
    need runtime validation + coercion (e.g. ensuring "difficulty" is one
    of an allowed set, catching missing fields) that Pydantic is built for.
    Config values, by contrast, are trusted/internal, so a plain dataclass
    was sufficient there.
==============================================================================
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


class DifficultyLevel(str, Enum):
    """Explanation / question difficulty tiers."""

    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


class NoteType(str, Enum):
    """Types of study artifacts the app can generate."""

    EXPLANATION = "explanation"
    INTERVIEW_QA = "interview_qa"
    QUIZ = "quiz"
    FLASHCARD = "flashcard"
    EXAMPLE = "example"
    EXERCISE = "exercise"


class TopicExplanation(BaseModel):
    """A single-level explanation of a topic."""

    level: DifficultyLevel
    content: str = Field(..., min_length=1, description="The explanation text.")


class InterviewQuestion(BaseModel):
    """One interview question with its model answer."""

    question: str = Field(..., min_length=1)
    answer: str = Field(..., min_length=1)
    difficulty: DifficultyLevel = DifficultyLevel.INTERMEDIATE

    @field_validator("question", "answer")
    @classmethod
    def not_blank(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("must not be blank")
        return value.strip()


class QuizQuestion(BaseModel):
    """A single multiple-choice quiz question."""

    question: str = Field(..., min_length=1)
    options: list[str] = Field(..., min_length=2, max_length=6)
    correct_answer_index: int = Field(..., ge=0)
    explanation: str = Field(default="", description="Why the correct answer is correct.")

    @field_validator("correct_answer_index")
    @classmethod
    def index_in_range(cls, value: int, info) -> int:
        # Cross-field validation: ensure the index actually points at a
        # real option. `info.data` holds already-validated fields.
        options = info.data.get("options")
        if options is not None and value >= len(options):
            raise ValueError(
                f"correct_answer_index {value} is out of range for {len(options)} options"
            )
        return value


class Flashcard(BaseModel):
    """A front/back flashcard."""

    front: str = Field(..., min_length=1)
    back: str = Field(..., min_length=1)


class CodingExercise(BaseModel):
    """A coding practice exercise with a starter template and solution."""

    title: str
    problem_statement: str
    starter_code: str = ""
    solution: str = ""
    hints: list[str] = Field(default_factory=list)


class StudyPackage(BaseModel):
    """
    The full bundle of generated study material for one topic — this is
    the top-level object returned by the orchestrating agent layer.
    """

    topic: str
    explanations: list[TopicExplanation] = Field(default_factory=list)
    interview_questions: list[InterviewQuestion] = Field(default_factory=list)
    quiz_questions: list[QuizQuestion] = Field(default_factory=list)
    flashcards: list[Flashcard] = Field(default_factory=list)
    real_world_examples: list[str] = Field(default_factory=list)
    coding_exercises: list[CodingExercise] = Field(default_factory=list)


class ChatTurn(BaseModel):
    """A single turn in a conversation, used for memory management."""

    model_config = ConfigDict(frozen=True)

    role: str = Field(..., pattern="^(user|assistant)$")
    content: str


class PDFQAResult(BaseModel):
    """Result of a RAG-based question answering call over an uploaded PDF."""

    question: str
    answer: str
    source_chunks: list[str] = Field(default_factory=list)
    confidence_note: Optional[str] = None
